arb-dir: lib/l10n # translation directory
template-arb-file: app_en.arb # name of file that contain translation
output-localization-file: app_localizations.dart # name of directory that contain generated code